### ISSUE TITLE
installation from version 1.0.0 fails under symfony2

### ISSUE THREAD

**Issue by tubssp** [dedicated-panel/PHPSeclibWrapperBundle#1]
Problem 1
    - Installation request for dedipanel/phpseclib-wrapper-bundle 1.0.0 -> satisfiable by dedipanel/phpseclib-wrapper-bundle[1.0.0].
    - dedipanel/phpseclib-wrapper-bundle 1.0.0 requires phpseclib/phpseclib 2.0.*@dev -> no matching package found.

**Comment by NiR-** [comment]
I have updated the README. You need to require phpseclib and the wrapper at the same time `
```
composer require phpseclib/phpseclib 2.0.*@dev
composer require dedipanel/phpseclib-wrapper-bundle ~1.0
.```

**Comment by NiR-** [comment]
@tubssp Is this working for you ? Can I close this issue ?
